### PR TITLE
Mike dev

### PR DESCRIPTION
**Pull request by AstrobioMike**
- building in methylSeq for `dpt-isa-to-runsheet` (one to test on is GLDS-397)

### CODE REVIEW

**Comment by AstrobioMike** [comment]
i did this pull request to this dev branch instead of main so the request didn't include all commits in J-81:development too ¯\_(ツ)_/¯

**Comment by J-81** [comment]
Looking good at first glance, I'll add a unittest to cover GLDS-397 tomorrow.

**Comment by AstrobioMike** [comment]
ready for your eyes, @J-81

**Comment by J-81** [comment]
@AstrobioMike Can you merge in the remote development, testing triggers for the test runner, thanks

**Comment by AstrobioMike** [comment]
attaching test isa zip: [GLDS-397_metadata_GLDS-397-ISA.zip](https://github.com/J-81/dp_tools/files/10117703/GLDS-397_metadata_GLDS-397-ISA.zip)

and relevant output spot from pytest (most are failing because i don't have any test files set up except this one):

image


Sorry, not sure what this means
> Can you merge in the remote development, testing triggers for the test runner

**Comment by J-81** [comment]
> attaching test isa zip: [GLDS-397_metadata_GLDS-397-ISA.zip](https://github.com/J-81/dp_tools/files/10117703/GLDS-397_metadata_GLDS-397-ISA.zip)
> 
> and relevant output spot from pytest (most are failing because i don't have any test files set up except this one):
> 
> image

Perfect!

> Sorry, not sure what this means
> 
> > Can you merge in the remote development, testing triggers for the test runner

Sorry I meant just re-merge the current development branch into your branch.  I had the tests only trigger on PR initial opens, now it should trigger when new commits are added to an existing PR (e.g. a merge of the current development branch).  While I'm sure you didn't break any of my existing tests, this will ensure github checks that as well via actions.

**Comment by AstrobioMike** [comment]
ah, gotcha!

**Pull request merged**
